Lecture 14 Series

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
obj =Series([3,6,7,8,9])

In [3]:
obj

0    3
1    6
2    7
3    8
4    9
dtype: int64

In [4]:
obj.values

array([3, 6, 7, 8, 9], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
ww2_cas = Series([8700000,4300000,3000000,2100000,400000],index=['USSR','Germany','China','Japan','USA'])
ww2_cas

USSR       8700000
Germany    4300000
China      3000000
Japan      2100000
USA         400000
dtype: int64

In [7]:
ww2_cas["USA"]

400000

In [8]:
ww2_cas["USSR"]

8700000

In [9]:
#Get Casualties greater than 4Million

In [10]:
ww2_cas[ww2_cas>4000000]

USSR       8700000
Germany    4300000
dtype: int64

In [11]:
"USSR" in ww2_cas

True

In [12]:
8700000 in ww2_cas

False

In [13]:
ww2_dict = ww2_cas.to_dict()  #Series to dictionary

In [14]:
ww2_dict

{'USSR': 8700000,
 'Germany': 4300000,
 'China': 3000000,
 'Japan': 2100000,
 'USA': 400000}

In [15]:
countries = ['China','Germany','Japan','USA','USSR','Argentina']
obj2=Series(ww2_cas,countries)

In [16]:
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
dtype: float64

In [17]:
pd.isnull(obj2)                       #Check Null Values in Series

China        False
Germany      False
Japan        False
USA          False
USSR         False
Argentina     True
dtype: bool

In [18]:
pd.notnull(obj2)                      #Check Not Null values

China         True
Germany       True
Japan         True
USA           True
USSR          True
Argentina    False
dtype: bool

In [19]:
ww2_cas+obj2                        #Add 2 Series

Argentina           NaN
China         6000000.0
Germany       8600000.0
Japan         4200000.0
USA            800000.0
USSR         17400000.0
dtype: float64

In [20]:
obj2.name="World War 2 Series"

In [21]:
obj2

China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: World War 2 Series, dtype: float64

In [22]:
obj2.index.name="Countries"

In [23]:
obj2

Countries
China        3000000.0
Germany      4300000.0
Japan        2100000.0
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: World War 2 Series, dtype: float64

Lecture 15 DataFrames

In [63]:
import webbrowser
websites='http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(websites)

True

In [64]:
nfl_frame=pd.read_clipboard()    # Copy from ClipBoard into a DataFrame

In [65]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North
3,4,Miami Dolphins,800,445,351,4,0.559,1966,AFC East
4,5,New England Patriots[b],884,489,386,9,0.558,1960,AFC East
5,6,Minnesota Vikings,870,470,390,10,0.546,1961,NFC North
6,7,Baltimore Ravens,352,190,161,1,0.541,1996,AFC North
7,8,New York Giants,"1,305",687,585,33,0.539,1925,NFC East
8,9,Denver Broncos,884,470,404,10,0.537,1960,AFC West
9,10,San Francisco 49ers,"1,002",528,460,14,0.534,1950,NFC West
10,11,Pittsburgh Steelers,"1,179",614,538,20,0.532,1933,AFC North
11,12,Oakland Raiders,884,462,411,11,0.529,1960,AFC West
12,13,Indianapolis Colts[c],966,506,453,7,0.527,1953,AFC South
13,14,Kansas City Chiefs,884,457,415,12,0.524,1960,AFC West
14,15,Seattle Seahawks,660,334,325,1,0.507,1976,NFC West
15,16,Washington Redskins,"1,202",595,581,28,0.506,1932,NFC East
16,17,Carolina Panthers,368,183,184,1,0.499,1995,NFC South
17,18,Los Angeles Chargers[d],884,435,438,11,0.498,1960,AFC West
18,19,Los Angeles Rams,"1,135",555,559,21,0.498,1937,NFC West
19,20,Cleveland Browns,954,462,482,10,0.490,1950,AFC North
20,21,Philadelphia Eagles,"1,188",568,594,26,0.489,1933,NFC East
21,22,Tennessee Titans,884,422,456,6,0.481,1960,AFC South
22,23,Buffalo Bills,884,409,467,8,0.467,1960,AFC East
23,24,Detroit Lions,"1,233",553,648,32,0.461,1930,NFC North
24,25,Cincinnati Bengals,772,351,417,4,0.457,1968,AFC North
25,26,New York Jets,884,397,479,8,0.454,1960,AFC East
26,27,Jacksonville Jaguars,368,165,203,0,0.448,1995,AFC South
27,28,New Orleans Saints,786,349,432,5,0.447,1967,NFC South
28,29,Atlanta Falcons,800,351,443,6,0.443,1966,NFC South
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South

In [66]:
nfl_frame.columns

Index(['Rank', 'Team', 'GP', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Division'],
      dtype='object')

In [67]:
nfl_frame["First NFL Season"] #Column Name Has More Than One Word

0     1960
1     1921
2     1920
3     1966
4     1960
5     1961
6     1996
7     1925
8     1960
9     1950
10    1933
11    1960
12    1953
13    1960
14    1976
15    1932
16    1995
17    1960
18    1937
19    1950
20    1933
21    1960
22    1960
23    1930
24    1968
25    1960
26    1995
27    1967
28    1966
29    2002
30    1920
31    1976
Name: First NFL Season, dtype: int64

In [68]:
DataFrame(nfl_frame,columns=['Rank', 'Team', 'GP', 'Won', 'Lost'])

    Rank                     Team     GP  Won  Lost
0      1           Dallas Cowboys    882  502   374
1      2        Green Bay Packers  1,336  737   562
2      3            Chicago Bears  1,370  749   579
3      4           Miami Dolphins    800  445   351
4      5  New England Patriots[b]    884  489   386
5      6        Minnesota Vikings    870  470   390
6      7         Baltimore Ravens    352  190   161
7      8          New York Giants  1,305  687   585
8      9           Denver Broncos    884  470   404
9     10      San Francisco 49ers  1,002  528   460
10    11      Pittsburgh Steelers  1,179  614   538
11    12          Oakland Raiders    884  462   411
12    13    Indianapolis Colts[c]    966  506   453
13    14       Kansas City Chiefs    884  457   415
14    15         Seattle Seahawks    660  334   325
15    16      Washington Redskins  1,202  595   581
16    17        Carolina Panthers    368  183   184
17    18  Los Angeles Chargers[d]    884  435   438
18    19         Los Angeles Rams  1,135  555   559
19    20         Cleveland Browns    954  462   482
20    21      Philadelphia Eagles  1,188  568   594
21    22         Tennessee Titans    884  422   456
22    23            Buffalo Bills    884  409   467
23    24            Detroit Lions  1,233  553   648
24    25       Cincinnati Bengals    772  351   417
25    26            New York Jets    884  397   479
26    27     Jacksonville Jaguars    368  165   203
27    28       New Orleans Saints    786  349   432
28    29          Atlanta Falcons    800  351   443
29    30           Houston Texans    256  110   146
30    31        Arizona Cardinals  1,330  550   740
31    32     Tampa Bay Buccaneers    660  255   404

In [69]:
nfl_frame.head(3)

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North

In [70]:
nfl_frame.tail(3)

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South

In [71]:
nfl_frame.ix[3]

C:\Users\kamat\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

Rank                             4
Team                Miami Dolphins
GP                             800
Won                            445
Lost                           351
Tied                             4
Pct.                         0.559
First NFL Season              1966
Division                  AFC East
Name: 3, dtype: object

In [72]:
nfl_frame['Stadium']="Levi's Stadium"

In [73]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division,Stadium
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East,Levi's Stadium
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North,Levi's Stadium
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North,Levi's Stadium
3,4,Miami Dolphins,800,445,351,4,0.559,1966,AFC East,Levi's Stadium
4,5,New England Patriots[b],884,489,386,9,0.558,1960,AFC East,Levi's Stadium
5,6,Minnesota Vikings,870,470,390,10,0.546,1961,NFC North,Levi's Stadium
6,7,Baltimore Ravens,352,190,161,1,0.541,1996,AFC North,Levi's Stadium
7,8,New York Giants,"1,305",687,585,33,0.539,1925,NFC East,Levi's Stadium
8,9,Denver Broncos,884,470,404,10,0.537,1960,AFC West,Levi's Stadium
9,10,San Francisco 49ers,"1,002",528,460,14,0.534,1950,NFC West,Levi's Stadium
10,11,Pittsburgh Steelers,"1,179",614,538,20,0.532,1933,AFC North,Levi's Stadium
11,12,Oakland Raiders,884,462,411,11,0.529,1960,AFC West,Levi's Stadium
12,13,Indianapolis Colts[c],966,506,453,7,0.527,1953,AFC South,Levi's Stadium
13,14,Kansas City Chiefs,884,457,415,12,0.524,1960,AFC West,Levi's Stadium
14,15,Seattle Seahawks,660,334,325,1,0.507,1976,NFC West,Levi's Stadium
15,16,Washington Redskins,"1,202",595,581,28,0.506,1932,NFC East,Levi's Stadium
16,17,Carolina Panthers,368,183,184,1,0.499,1995,NFC South,Levi's Stadium
17,18,Los Angeles Chargers[d],884,435,438,11,0.498,1960,AFC West,Levi's Stadium
18,19,Los Angeles Rams,"1,135",555,559,21,0.498,1937,NFC West,Levi's Stadium
19,20,Cleveland Browns,954,462,482,10,0.490,1950,AFC North,Levi's Stadium
20,21,Philadelphia Eagles,"1,188",568,594,26,0.489,1933,NFC East,Levi's Stadium
21,22,Tennessee Titans,884,422,456,6,0.481,1960,AFC South,Levi's Stadium
22,23,Buffalo Bills,884,409,467,8,0.467,1960,AFC East,Levi's Stadium
23,24,Detroit Lions,"1,233",553,648,32,0.461,1930,NFC North,Levi's Stadium
24,25,Cincinnati Bengals,772,351,417,4,0.457,1968,AFC North,Levi's Stadium
25,26,New York Jets,884,397,479,8,0.454,1960,AFC East,Levi's Stadium
26,27,Jacksonville Jaguars,368,165,203,0,0.448,1995,AFC South,Levi's Stadium
27,28,New Orleans Saints,786,349,432,5,0.447,1967,NFC South,Levi's Stadium
28,29,Atlanta Falcons,800,351,443,6,0.443,1966,NFC South,Levi's Stadium
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South,Levi's Stadium
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West,Levi's Stadium
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South,Levi's Stadium

In [75]:
nfl_frame["Stadium"]=np.arange(32)

In [76]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division,Stadium
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East,0
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North,1
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North,2
3,4,Miami Dolphins,800,445,351,4,0.559,1966,AFC East,3
4,5,New England Patriots[b],884,489,386,9,0.558,1960,AFC East,4
5,6,Minnesota Vikings,870,470,390,10,0.546,1961,NFC North,5
6,7,Baltimore Ravens,352,190,161,1,0.541,1996,AFC North,6
7,8,New York Giants,"1,305",687,585,33,0.539,1925,NFC East,7
8,9,Denver Broncos,884,470,404,10,0.537,1960,AFC West,8
9,10,San Francisco 49ers,"1,002",528,460,14,0.534,1950,NFC West,9
10,11,Pittsburgh Steelers,"1,179",614,538,20,0.532,1933,AFC North,10
11,12,Oakland Raiders,884,462,411,11,0.529,1960,AFC West,11
12,13,Indianapolis Colts[c],966,506,453,7,0.527,1953,AFC South,12
13,14,Kansas City Chiefs,884,457,415,12,0.524,1960,AFC West,13
14,15,Seattle Seahawks,660,334,325,1,0.507,1976,NFC West,14
15,16,Washington Redskins,"1,202",595,581,28,0.506,1932,NFC East,15
16,17,Carolina Panthers,368,183,184,1,0.499,1995,NFC South,16
17,18,Los Angeles Chargers[d],884,435,438,11,0.498,1960,AFC West,17
18,19,Los Angeles Rams,"1,135",555,559,21,0.498,1937,NFC West,18
19,20,Cleveland Browns,954,462,482,10,0.490,1950,AFC North,19
20,21,Philadelphia Eagles,"1,188",568,594,26,0.489,1933,NFC East,20
21,22,Tennessee Titans,884,422,456,6,0.481,1960,AFC South,21
22,23,Buffalo Bills,884,409,467,8,0.467,1960,AFC East,22
23,24,Detroit Lions,"1,233",553,648,32,0.461,1930,NFC North,23
24,25,Cincinnati Bengals,772,351,417,4,0.457,1968,AFC North,24
25,26,New York Jets,884,397,479,8,0.454,1960,AFC East,25
26,27,Jacksonville Jaguars,368,165,203,0,0.448,1995,AFC South,26
27,28,New Orleans Saints,786,349,432,5,0.447,1967,NFC South,27
28,29,Atlanta Falcons,800,351,443,6,0.443,1966,NFC South,28
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South,29
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West,30
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South,31

In [50]:
# Add Series to a data frame

In [77]:
 stadiums = Series(["Levi's Stadium","AT&T Stadium"],index=[4,0])

In [78]:
nfl_frame["Stadium"]=stadiums

In [79]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division,Stadium
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East,AT&T Stadium
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North,NaN
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North,NaN
3,4,Miami Dolphins,800,445,351,4,0.559,1966,AFC East,NaN
4,5,New England Patriots[b],884,489,386,9,0.558,1960,AFC East,Levi's Stadium
5,6,Minnesota Vikings,870,470,390,10,0.546,1961,NFC North,NaN
6,7,Baltimore Ravens,352,190,161,1,0.541,1996,AFC North,NaN
7,8,New York Giants,"1,305",687,585,33,0.539,1925,NFC East,NaN
8,9,Denver Broncos,884,470,404,10,0.537,1960,AFC West,NaN
9,10,San Francisco 49ers,"1,002",528,460,14,0.534,1950,NFC West,NaN
10,11,Pittsburgh Steelers,"1,179",614,538,20,0.532,1933,AFC North,NaN
11,12,Oakland Raiders,884,462,411,11,0.529,1960,AFC West,NaN
12,13,Indianapolis Colts[c],966,506,453,7,0.527,1953,AFC South,NaN
13,14,Kansas City Chiefs,884,457,415,12,0.524,1960,AFC West,NaN
14,15,Seattle Seahawks,660,334,325,1,0.507,1976,NFC West,NaN
15,16,Washington Redskins,"1,202",595,581,28,0.506,1932,NFC East,NaN
16,17,Carolina Panthers,368,183,184,1,0.499,1995,NFC South,NaN
17,18,Los Angeles Chargers[d],884,435,438,11,0.498,1960,AFC West,NaN
18,19,Los Angeles Rams,"1,135",555,559,21,0.498,1937,NFC West,NaN
19,20,Cleveland Browns,954,462,482,10,0.490,1950,AFC North,NaN
20,21,Philadelphia Eagles,"1,188",568,594,26,0.489,1933,NFC East,NaN
21,22,Tennessee Titans,884,422,456,6,0.481,1960,AFC South,NaN
22,23,Buffalo Bills,884,409,467,8,0.467,1960,AFC East,NaN
23,24,Detroit Lions,"1,233",553,648,32,0.461,1930,NFC North,NaN
24,25,Cincinnati Bengals,772,351,417,4,0.457,1968,AFC North,NaN
25,26,New York Jets,884,397,479,8,0.454,1960,AFC East,NaN
26,27,Jacksonville Jaguars,368,165,203,0,0.448,1995,AFC South,NaN
27,28,New Orleans Saints,786,349,432,5,0.447,1967,NFC South,NaN
28,29,Atlanta Falcons,800,351,443,6,0.443,1966,NFC South,NaN
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South,NaN
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West,NaN
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South,NaN

In [80]:
del nfl_frame["Stadium"]     # Delete Stadium column

In [81]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,882,502,374,6,0.573,1960,NFC East
1,2,Green Bay Packers,"1,336",737,562,37,0.565,1921,NFC North
2,3,Chicago Bears,"1,370",749,579,42,0.562,1920,NFC North
3,4,Miami Dolphins,800,445,351,4,0.559,1966,AFC East
4,5,New England Patriots[b],884,489,386,9,0.558,1960,AFC East
5,6,Minnesota Vikings,870,470,390,10,0.546,1961,NFC North
6,7,Baltimore Ravens,352,190,161,1,0.541,1996,AFC North
7,8,New York Giants,"1,305",687,585,33,0.539,1925,NFC East
8,9,Denver Broncos,884,470,404,10,0.537,1960,AFC West
9,10,San Francisco 49ers,"1,002",528,460,14,0.534,1950,NFC West
10,11,Pittsburgh Steelers,"1,179",614,538,20,0.532,1933,AFC North
11,12,Oakland Raiders,884,462,411,11,0.529,1960,AFC West
12,13,Indianapolis Colts[c],966,506,453,7,0.527,1953,AFC South
13,14,Kansas City Chiefs,884,457,415,12,0.524,1960,AFC West
14,15,Seattle Seahawks,660,334,325,1,0.507,1976,NFC West
15,16,Washington Redskins,"1,202",595,581,28,0.506,1932,NFC East
16,17,Carolina Panthers,368,183,184,1,0.499,1995,NFC South
17,18,Los Angeles Chargers[d],884,435,438,11,0.498,1960,AFC West
18,19,Los Angeles Rams,"1,135",555,559,21,0.498,1937,NFC West
19,20,Cleveland Browns,954,462,482,10,0.490,1950,AFC North
20,21,Philadelphia Eagles,"1,188",568,594,26,0.489,1933,NFC East
21,22,Tennessee Titans,884,422,456,6,0.481,1960,AFC South
22,23,Buffalo Bills,884,409,467,8,0.467,1960,AFC East
23,24,Detroit Lions,"1,233",553,648,32,0.461,1930,NFC North
24,25,Cincinnati Bengals,772,351,417,4,0.457,1968,AFC North
25,26,New York Jets,884,397,479,8,0.454,1960,AFC East
26,27,Jacksonville Jaguars,368,165,203,0,0.448,1995,AFC South
27,28,New Orleans Saints,786,349,432,5,0.447,1967,NFC South
28,29,Atlanta Falcons,800,351,443,6,0.443,1966,NFC South
29,30,Houston Texans,256,110,146,0,0.430,2002,AFC South
30,31,Arizona Cardinals,"1,330",550,740,40,0.429,1920,NFC West
31,32,Tampa Bay Buccaneers,660,255,404,1,0.387,1976,NFC South

In [82]:
data = {'City':['SF','LA','NYC'],
        'Population':[837000,3880000,8400000]}

In [83]:
city_frame = DataFrame(data)

#Show
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

In [84]:
#For full list of ways to create DataFrames from various sources go to teh documentation for pandas:
website = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.html'
webbrowser.open(website)

True